--Ethnic Units
UPDATE Civilizations SET ArtStyleSuffix = 
	( CASE WHEN EXISTS(SELECT ArtStyleSuffix FROM Civilizations WHERE ArtStyleSuffix = "_EGYPT")
		THEN "_EGYPT"
		ELSE "_AFRI" END
	) WHERE Type = "CIVILIZATION_ANCIENT_LIBYA_MOD";

--Historical Religions
UPDATE Civilization_Religions SET ReligionType = 
	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_AMANAIISM' )
		THEN 'RELIGION_AMANAIISM'
		ELSE ( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_PESEDJET' )
		THEN 'RELIGION_PESEDJET'
		ELSE 'RELIGION_ISLAM' END ) END
	) WHERE CivilizationType = 'CIVILIZATION_ANCIENT_LIBYA_MOD';

CREATE TRIGGER ReligionGaraSupportAmun
AFTER INSERT ON Religions WHEN 'RELIGION_AMANAIISM' = NEW.Type
BEGIN
	UPDATE Civilization_Religions 
	SET ReligionType = 'RELIGION_AMANAIISM'
	WHERE CivilizationType IN ('CIVILIZATION_ANCIENT_LIBYA_MOD');
END;

CREATE TRIGGER ReligionGaraSupportPesedject
AFTER INSERT ON Religions WHEN 'RELIGION_PESEDJET' = NEW.Type
BEGIN
	UPDATE Civilization_Religions SET ReligionType = 
		( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_AMANAIISM' )
			THEN 'RELIGION_AMANAIISM'
			ELSE 'RELIGION_PESEDJET' END 
		) WHERE CivilizationType = 'CIVILIZATION_ANCIENT_LIBYA_MOD';
END;

--Nazca
UPDATE Features SET Description =
	( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type="CIVILIZATION_NAZCA" )
		THEN "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_MOD"
		ELSE "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER" END
    ) WHERE Type = "FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER";

UPDATE Features SET Civilopedia =
	( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type="CIVILIZATION_NAZCA" )
		THEN "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_MOD_TEXT"
		ELSE "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_TEXT" END
    ) WHERE Type = "FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER";

CREATE TRIGGER TerrainGaraSupportNazca
AFTER INSERT ON Features WHEN 'FEATURE_AQUIFER' = NEW.Type
BEGIN

	UPDATE Features SET Description =
		( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type="CIVILIZATION_NAZCA" )
			THEN "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_MOD"
			ELSE "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER" END
		) WHERE Type = "FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER";

	UPDATE Features SET Civilopedia =
		( CASE WHEN EXISTS(SELECT Type FROM Civilizations WHERE Type="CIVILIZATION_NAZCA" )
			THEN "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_MOD_TEXT"
			ELSE "TXT_KEY_FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER_TEXT" END
		) WHERE Type = "FEATURE_ANCIENT_LIBYAN_MOD_FOSSIL_WATER";

END;

--Map Labels
CREATE TABLE IF NOT EXISTS ML_CivCultures (ID INTEGER PRIMARY KEY AUTOINCREMENT, CivType TEXT, CultureType TEXT, CultureEra TEXT DEFAULT 'ANY');
INSERT INTO ML_CivCultures
			(CivType,						        CultureType,	CultureEra)
VALUES		('CIVILIZATION_ANCIENT_LIBYA_MOD',		  'ARABIAN',		 'ANY'),
			('CIVILIZATION_ANCIENT_LIBYA_MOD',		  'AFRICAN',	     'ANY');

--Piety
INSERT OR REPLACE INTO Flavors
            (Type)
VALUES      ('FLAVOR_JFD_RELIGIOUS_INTOLERANCE');
 
INSERT INTO Leader_Flavors
            (LeaderType,									        FlavorType,    Flavor)
VALUES      ('LEADER_ANCIENT_LIBYA_MOD',    'FLAVOR_JFD_RELIGIOUS_INTOLERANCE',         2);