--==========================================================================================================================
-- Civilization_JFD_CultureTypes
--==========================================================================================================================
CREATE TABLE IF NOT EXISTS Civilization_JFD_CultureTypes(CivilizationType, ArtDefineTag, CultureType, SplashScreenTag, SoundtrackTag);

INSERT OR REPLACE INTO Civilization_JFD_CultureTypes
			(CivilizationType,	ArtDefineTag,		CultureType,			SplashScreenTag,		SoundtrackTag)
VALUES		('CIVILIZATION_KHMER_LS_MOD', '_JFD_MANDALA',	'CULTURE_JFD_MANDALA',	'JFD_Mandala',	'JFD_Mandala');
--==========================================================================================================================
--==========================================================================================================================

--==========================================================================================================================	
-- Diplomacy_Responses
--==========================================================================================================================			
INSERT INTO Diplomacy_Responses 
			(LeaderType, 				ResponseType, 											Response, 																		Bias)
VALUES		('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_FIRSTGREETING%', 									2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DEFEATED%', 										2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_REPEAT_TOO_MUCH%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_REPEAT_TRADE_TOO_MUCH%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_REPEAT_TOO_MUCH%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_HELLO%', 						2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_POLITE_HELLO%', 							2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_HUMAN_AT_WAR%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HUMAN_AT_WAR%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 			2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_AGGRESSIVE_MILITARY_WARNING%', 					2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 		2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_AGGRESSIVE_PLOT_BUYING%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 			2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_AGGRESSIVE_EXPANSION%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_FRIENDLY_STRONG_MILITARY%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_FRIENDLY_STRONG_ECONOMY%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 			2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_TOO_SOON_FOR_DOF', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_TOO_SOON_FOR_DOF%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DENOUNCE%', 										2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DENOUNCE%', 										2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DOFED_FRIEND', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DOFED_FRIEND%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DOFED_ENEMY', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DOFED_ENEMY%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DENOUNCED_ENEMY', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DENOUNCED_ENEMY%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DENOUNCED_FRIEND', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DENOUNCED_FRIEND%', 						2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DOF_SO_AI_DOF', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DOF_SO_AI_DOF%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DENOUNCE_SO_AI_DENOUNCE%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_HUMAN_DOF_SO_AI_DENOUNCE%', 						2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_COOP_WAR_REQUEST', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_COOP_WAR_REQUEST%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_COOP_WAR_TIME', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_COOP_WAR_TIME%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_WORK_WITH_US', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DEC_FRIENDSHIP%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_PLOT_BUYING_WARNING', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_PLOT_BUYING_WARNING%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_PLOT_BUYING_SERIOUS_WARNING%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_EXPANSION_SERIOUS_WARNING%', 						2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_EXPANSION_WARNING', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_EXPANSION_WARNING%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_AGGRESSIVE_MILITARY_WARNING%', 					2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_UNHAPPINESS', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_UNHAPPINESS%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_CITIES', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_CITIES%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_BULLY', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_BULLY%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_MILITARY', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_MILITARY%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_GENERIC', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_JFD_LOUIS_XIV%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_CULTURE', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_CULTURE%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_INSULT_POPULATION', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_INSULT_POPULATION%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_RETURNED_CIVILIAN', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_CIVILIAN%', 										2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DECLARATION_PROTECT_CITY_STATE', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DECLARATION_PROTECT_CITY_STATE%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DECLARATION_ABANDON_CITY_STATE', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DECLARATION_ABANDON_CITY_STATE%', 				2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DONT_SETTLE_YES%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DONT_SETTLE_NO%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_LUXURY_TRADE', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_LUXURY_TRADE%', 									2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_OPEN_BORDERS_EXCHANGE%', 							2),	
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_REQUEST', 									'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_RESPONSE_REQUEST%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_HOSTILE%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_HOSTILE%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_HOSTILE%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_EXCITED%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_EXCITED%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_EXCITED%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_SAD%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_ATTACKED_BETRAYED%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DOW_GENERIC%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DOW_LAND%', 										2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DOW_WORLD_CONQUEST%', 							2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DOW_OPPORTUNITY%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_DOW_DESPERATE%', 									2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_TOO_SOON_NO_PEACE%', 								2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',	'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GOOD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GOOD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GOOD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_WE_ATTACKED_MINOR_BAD',						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_GOOD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD', 	'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_ATTACKED_MINOR_BAD', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 			'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_WE_ATTACKED_MINOR_GOOD', 						'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD', 					'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD', 		'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2),
			('LEADER_KHMER_LS_MOD_SURYAVARMAN_II', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD', 				'TXT_KEY_LEADER_KHMER_LS_MOD_SURYAVARMAN_II_BAD%', 											2);		
--==========================================================================================================================			
--==========================================================================================================================						

--------------------------------------------------------------------------------------------------
--Icon Atlas 
--------------------------------------------------------------------------------------------------
INSERT INTO IconTextureAtlases (Atlas,	IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
SELECT 'FA_UB_ATLAS_KHMER',					256,		5,				5,				'UBAtlas256_khmer.dds' UNION ALL
SELECT 'FA_UB_ATLAS_KHMER',					128,		5,				5,				'UBAtlas128_khmer.dds' UNION ALL
SELECT 'FA_UB_ATLAS_KHMER',					80,			5,				5,				'UBAtlas80_khmer.dds' UNION ALL
SELECT 'FA_UB_ATLAS_KHMER',					64,			5,				5,				'UBAtlas64_khmer.dds' UNION ALL
SELECT 'FA_UB_ATLAS_KHMER',					45,			5,				5,				'UBAtlas45_khmer.dds';

--------------------------------------------------------------------------------------------------
--Font Mapping
-------------------------------------------------------------------------------------------------- 
--INSERT INTO IconFontTextures (IconFontTexture,	IconFontTextureFile)
--SELECT 'ICON_FONT_TEXTURE_UB',					'UB-FontIcons';

--------------------------------------------------------------------------------------------------
--Resources
--------------------------------------------------------------------------------------------------
INSERT INTO Resources (Type, CivilizationType,	ResourceClassType,		Hills,	Flatlands,	MaxLatitude,	TechReveal,		TechCityTrade,			IconAtlas,				PortraitIndex,	ArtDefineTag,					IconString,					Description,					Civilopedia,								Help,									AITradeModifier,	ResourceUsage,	AIObjective,	PlacementOrder,	ConstAppearance,	MinAreaSize,	Player,		Normalize)
SELECT 'RESOURCE_FA_RICE', NULL,		'RESOURCECLASS_BONUS',	0,		1,			50,				NULL,			'TECH_AGRICULTURE',		'CIV_DJSH_KHMER_ATLAS',	6,				'ART_DEF_RESOURCE_FA_RICE',		'[ICON_RES_FA_RICE]',		'TXT_KEY_RESOURCE_FA_RICE',		'TXT_KEY_CIV5_RESOURCE_FA_RICE_TEXT',		'TXT_KEY_RESOURCE_FA_RICE_HELP',		0,					0,				0,				3,				50,					3,				0,			1 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT', 'CIVILIZATION_KHMER_LS_MOD',		'RESOURCECLASS_BONUS',	0,		1,			50,				NULL,			'TECH_CALENDAR',		'CIV_DJSH_KHMER_ATLAS',	4,				'ART_DEF_RESOURCE_DJSH_COCONUT',		'[ICON_RES_DJSH_COCONUT]',		'TXT_KEY_RESOURCE_DJSH_COCONUT',		'TXT_KEY_CIV5_RESOURCE_DJSH_COCONUT_TEXT',		'TXT_KEY_RESOURCE_DJSH_COCONUT_HELP',		0,					0,				0,				3,				50,					3,				0,			1 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO', 'CIVILIZATION_KHMER_LS_MOD',		'RESOURCECLASS_BONUS',	0,		1,			50,				NULL,			'TECH_CALENDAR',		'CIV_DJSH_KHMER_ATLAS',	5,				'ART_DEF_RESOURCE_DJSH_MANGO',		'[ICON_RES_DJSH_MANGO]',		'TXT_KEY_RESOURCE_DJSH_MANGO',		'TXT_KEY_CIV5_RESOURCE_DJSH_MANGO_TEXT',		'TXT_KEY_RESOURCE_DJSH_MANGO_HELP',		0,					0,				0,				3,				50,					3,				0,			1;
--------------------------------------------------------------------------------------------------
--Resource Yield Changes
--------------------------------------------------------------------------------------------------
INSERT INTO Resource_YieldChanges (ResourceType,	YieldType,			Yield)
SELECT 'RESOURCE_FA_RICE',							'YIELD_FOOD',		1 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',							'YIELD_FOOD',		1 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',							'YIELD_FOOD',		1;

--------------------------------------------------------------------------------------------------
--Resource Flavors
--------------------------------------------------------------------------------------------------
INSERT INTO Resource_Flavors (ResourceType,	FlavorType,				Flavor)
SELECT 'RESOURCE_FA_RICE',					'FLAVOR_GROWTH',		40 UNION ALL
SELECT 'RESOURCE_FA_RICE',					'FLAVOR_GOLD',			10 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',					'FLAVOR_GROWTH',		40 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',					'FLAVOR_CULTURE',		20 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',					'FLAVOR_GOLD',			10 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',					'FLAVOR_GROWTH',		40 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',					'FLAVOR_CULTURE',		20 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',					'FLAVOR_GOLD',			10;

--------------------------------------------------------------------------------------------------
--Resource Terrains
--------------------------------------------------------------------------------------------------
INSERT INTO Resource_TerrainBooleans (ResourceType,	TerrainType)
SELECT 'RESOURCE_FA_RICE',							'TERRAIN_PLAINS' UNION ALL
SELECT 'RESOURCE_FA_RICE',							'TERRAIN_GRASS' UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',							'TERRAIN_PLAINS' UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',							'TERRAIN_GRASS' UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',							'TERRAIN_PLAINS' UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',							'TERRAIN_GRASS';

--------------------------------------------------------------------------------------------------
--Resource Features
--------------------------------------------------------------------------------------------------
INSERT INTO Resource_FeatureBooleans (ResourceType,	FeatureType)
SELECT 'RESOURCE_FA_RICE',							'FEATURE_MARSH' UNION ALL
SELECT 'RESOURCE_FA_RICE',							'FEATURE_FLOOD_PLAINS' UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',							'FEATURE_JUNGLE' UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',							'FEATURE_FLOOD_PLAINS' UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',							'FEATURE_FOREST';

--------------------------------------------------------------------------------------------------
--Resource Feature Terrains
--------------------------------------------------------------------------------------------------
--INSERT INTO Resource_FeatureTerrainBooleans (ResourceType,	TerrainType)
--SELECT 'RESOURCE_FA_RICE',									'TERRAIN_DESERT' UNION ALL
--SELECT 'RESOURCE_DJSH_COCONUT',									'TERRAIN_DESERT' UNION ALL
--SELECT 'RESOURCE_DJSH_MANGO',									'TERRAIN_DESERT';

--------------------------------------------------------------------------------------------------
--Resource Improvements
--------------------------------------------------------------------------------------------------
INSERT INTO Improvement_ResourceTypes (ResourceType,	ImprovementType)
SELECT 'RESOURCE_FA_RICE',								'IMPROVEMENT_FARM' UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',								'IMPROVEMENT_PLANTATION' UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',								'IMPROVEMENT_PLANTATION';
--------------------------------------------------------------------------------------------------
--Resource Improvement Yields
--------------------------------------------------------------------------------------------------
INSERT INTO Improvement_ResourceType_Yields (ResourceType,	ImprovementType,			YieldType,			Yield)
SELECT 'RESOURCE_FA_RICE',									'IMPROVEMENT_FARM',	'YIELD_FOOD',		1 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',									'IMPROVEMENT_PLANTATION',	'YIELD_PRODUCTION',		1 UNION ALL
SELECT 'RESOURCE_DJSH_COCONUT',									'IMPROVEMENT_PLANTATION',	'YIELD_CULTURE',		2 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',									'IMPROVEMENT_PLANTATION',	'YIELD_FOOD',		1 UNION ALL
SELECT 'RESOURCE_DJSH_MANGO',									'IMPROVEMENT_PLANTATION',	'YIELD_CULTURE',		2;

--------------------------------------------------------------------------------------------------
--Font Textures
-------------------------------------------------------------------------------------------------- 
INSERT INTO IconFontTextures (IconFontTexture,	IconFontTextureFile) 
SELECT 'ICON_FONT_TEXTURE_FA_RICE',				'rice-fonticons' UNION ALL
SELECT 'ICON_FONT_TEXTURE_DJSH_COCONUT',				'coconut-fonticons' UNION ALL
SELECT 'ICON_FONT_TEXTURE_DJSH_MANGO',				'mango-fonticons';

--------------------------------------------------------------------------------------------------
--Font Mapping
-------------------------------------------------------------------------------------------------- 
INSERT INTO IconFontMapping (IconName,	IconFontTexture,					IconMapping) 
SELECT 'ICON_RES_FA_RICE',				'ICON_FONT_TEXTURE_FA_RICE',		1 UNION ALL
SELECT 'ICON_RES_DJSH_COCONUT',				'ICON_FONT_TEXTURE_DJSH_COCONUT',		1 UNION ALL
SELECT 'ICON_RES_DJSH_MANGO',				'ICON_FONT_TEXTURE_DJSH_MANGO',		1;

--------------------------------------------------------------------------------------------------
--SV Icons
-------------------------------------------------------------------------------------------------- 
INSERT INTO ArtDefine_StrategicView (StrategicViewType, TileType,		Asset)
SELECT 'ART_DEF_RESOURCE_FA_RICE',						'Resource',		'SV_Rice.dds' UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',						'Resource',		'SV_Coconut.dds' UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',						'Resource',		'SV_Mango.dds';

--------------------------------------------------------------------------------------------------
--Artdefines
-------------------------------------------------------------------------------------------------- 
INSERT INTO ArtDefine_LandmarkTypes (Type,	LandmarkType,	FriendlyName)
SELECT 'ART_DEF_RESOURCE_FA_RICE',			'Resource',		'Rice' UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',			'Resource',		'Coconut' UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',			'Resource',		'Mango';

INSERT INTO ArtDefine_Landmarks (ResourceType,	ImprovementType,					Model,								Era,			State,					Scale,				LayoutHandler,	TerrainContour)
SELECT 'ART_DEF_RESOURCE_FA_RICE',				'ART_DEF_IMPROVEMENT_NONE',			'resource_rice.fxsxml',				'Any',			'Any',					0.9399999976158142,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_FA_RICE',				'ART_DEF_IMPROVEMENT_FARM',	'hb_plantation_ind_rice.fxsxml',	'Any',		'UnderConstruction',	0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_FA_RICE',				'ART_DEF_IMPROVEMENT_FARM',	'plantation_ind_rice.fxsxml',		'Any',		'Constructed',			0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_FA_RICE',				'ART_DEF_IMPROVEMENT_FARM',	'pl_plantation_ind_rice.fxsxml',	'Any',		'Pillaged',				0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_NONE',			'coconuttrees.fxsxml',				'Any',			'Any',					0.9399999976158142,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees_hb.fxsxml',	'Ancient',		'UnderConstruction',	0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees.fxsxml',		'Ancient',		'Constructed',			0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees_pil.fxsxml',	'Ancient',		'Pillaged',				0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees_hbe.fxsxml',	'Industrial',	'UnderConstruction',	0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees.fxsxml',		'Industrial',	'Constructed',			0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_COCONUT',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_coconuttrees_pil.fxsxml',	'Industrial',	'Pillaged',				0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_NONE',			'mangotrees.fxsxml',				'Any',			'Any',					0.9399999976158142,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees_hb.fxsxml',	'Ancient',		'UnderConstruction',	0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees.fxsxml',		'Ancient',		'Constructed',			0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees_pil.fxsxml',	'Ancient',		'Pillaged',				0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees_hb.fxsxml',	'Industrial',	'UnderConstruction',	0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees.fxsxml',		'Industrial',	'Constructed',			0.9599999785423279,	'SNAPSHOT',		1 UNION ALL
SELECT 'ART_DEF_RESOURCE_DJSH_MANGO',				'ART_DEF_IMPROVEMENT_PLANTATION',	'plantation_ind_mangotrees_pil.fxsxml',	'Industrial',	'Pillaged',				0.9599999785423279,	'SNAPSHOT',		1;