--==========================================================================================================================	
-- Diplomacy_Responses
--==========================================================================================================================			
INSERT INTO Diplomacy_Responses 
			(LeaderType, 				ResponseType, 											Response, 																		Bias)
VALUES		('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_FIRSTGREETING%', 									2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DEFEATED%', 										2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_REPEAT_TOO_MUCH%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_REPEAT_TRADE_TOO_MUCH%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_REPEAT_TOO_MUCH%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_HELLO%', 						2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_POLITE_HELLO%', 							2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_HUMAN_AT_WAR%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HUMAN_AT_WAR%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 			2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_AGGRESSIVE_MILITARY_WARNING%', 					2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 		2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_AGGRESSIVE_PLOT_BUYING%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 			2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_AGGRESSIVE_EXPANSION%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_FRIENDLY_STRONG_MILITARY%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_FRIENDLY_STRONG_ECONOMY%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 			2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_TOO_SOON_FOR_DOF', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_TOO_SOON_FOR_DOF%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DENOUNCE%', 										2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DENOUNCE%', 										2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_RESPONSE_TO_BEING_DENOUNCED%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DOFED_FRIEND', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DOFED_FRIEND%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DOFED_ENEMY', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DOFED_ENEMY%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DENOUNCED_ENEMY', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DENOUNCED_ENEMY%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DENOUNCED_FRIEND', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DENOUNCED_FRIEND%', 						2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DOF_SO_AI_DOF', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DOF_SO_AI_DOF%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DENOUNCE_SO_AI_DENOUNCE%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_HUMAN_DOF_SO_AI_DENOUNCE%', 						2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_COOP_WAR_REQUEST', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_COOP_WAR_REQUEST%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_COOP_WAR_TIME', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_COOP_WAR_TIME%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_WORK_WITH_US', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DEC_FRIENDSHIP%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_PLOT_BUYING_WARNING', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_PLOT_BUYING_WARNING%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_PLOT_BUYING_SERIOUS_WARNING%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_EXPANSION_SERIOUS_WARNING%', 						2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_EXPANSION_WARNING', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_EXPANSION_WARNING%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_AGGRESSIVE_MILITARY_WARNING%', 					2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_UNHAPPINESS', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_UNHAPPINESS%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_CITIES', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_CITIES%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_BULLY', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_BULLY%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_MILITARY', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_MILITARY%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_GENERIC', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_JFD_LOUIS_XIV%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_CULTURE', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_CULTURE%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_INSULT_POPULATION', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_INSULT_POPULATION%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_RETURNED_CIVILIAN', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_CIVILIAN%', 										2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DECLARATION_PROTECT_CITY_STATE', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DECLARATION_PROTECT_CITY_STATE%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DECLARATION_ABANDON_CITY_STATE', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DECLARATION_ABANDON_CITY_STATE%', 				2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DONT_SETTLE_YES%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DONT_SETTLE_NO%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_LUXURY_TRADE', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_LUXURY_TRADE%', 									2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_OPEN_BORDERS_EXCHANGE%', 							2),	
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_REQUEST', 									'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_RESPONSE_REQUEST%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_HOSTILE%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_HOSTILE%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_HOSTILE%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_EXCITED%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_EXCITED%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_EXCITED%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_SAD%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_ATTACKED_BETRAYED%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DOW_GENERIC%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DOW_LAND%', 										2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DOW_WORLD_CONQUEST%', 							2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DOW_OPPORTUNITY%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_DOW_DESPERATE%', 									2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_TOO_SOON_NO_PEACE%', 								2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',	'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GOOD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GOOD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GOOD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_WE_ATTACKED_MINOR_BAD',						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_GOOD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD', 	'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_ATTACKED_MINOR_BAD', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 			'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_WE_ATTACKED_MINOR_GOOD', 						'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD', 					'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD', 		'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2),
			('LEADER_FLANDERS_LS_MOD_ROBERTIII', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD', 				'TXT_KEY_LEADER_FLANDERS_LS_MOD_ROBERTIII_BAD%', 											2);		
--==========================================================================================================================			
--==========================================================================================================================	
INSERT INTO Language_en_US (Tag, Text)
SELECT 'TXT_KEY_BUILD_MARSH_FLANDERS', 'Create a Marsh'  UNION ALL
SELECT 'TXT_KEY_BUILD_MARSH_FLANDERS_HELP', 'Terraforms the landscape here into the Marsh. Yields are AI valuation.'  UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH_FLANDERS', 'Marsh' UNION ALL
SELECT 'TXT_KEY_CIV5_IMPROVEMENTS_MARSH_FLANDERS', 'To restore the marshlands on any terrain, just allow water to flow to it naturally. It should even work on snow! If the water doesn''t freeze that is.' UNION ALL
SELECT 'TXT_KEY_IMPROVEMENT_MARSH_FLANDERS_HELP', 'The Flemish people may begin powerful restoration projects of marshlands.';

INSERT INTO Builds (Type, Time, ImprovementType, Description, Help, EntityEvent, HotKey, OrderPriority, IconIndex, IconAtlas)
SELECT 'BUILD_MARSH_FLANDERS', 700, 'IMPROVEMENT_MARSH_FLANDERS', 'TXT_KEY_BUILD_MARSH_FLANDERS', 'TXT_KEY_BUILD_MARSH_FLANDERS_HELP', 'ENTITY_EVENT_IRRIGATE', 'KB_L', 97, 0, 'EXPANSION_UNIT_ACTION_ATLAS';

INSERT INTO Unit_Builds (UnitType, BuildType)
SELECT 'UNIT_WORKER', 'BUILD_MARSH_FLANDERS';

INSERT INTO BuildFeatures (BuildType, FeatureType, PrereqTech, Time, Production, Remove)
SELECT 'BUILD_MARSH_FLANDERS', 'FEATURE_JUNGLE', 'TECH_IRON_WORKING', 500, 20, 1 UNION ALL
SELECT 'BUILD_MARSH_FLANDERS', 'FEATURE_FOREST', 'TECH_BRONZE_WORKING', 300, 20, 1 UNION ALL
SELECT 'BUILD_MARSH_FLANDERS', 'FEATURE_MARSH', 'TECH_FUTURE_TECH', 300, 20, 1;

INSERT INTO Improvements (Type, Description, Civilopedia, Help, ArtDefineTag, PortraitIndex, IconAtlas)
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TXT_KEY_IMPROVEMENT_MARSH_FLANDERS', 'TXT_KEY_CIV5_IMPROVEMENTS_MARSH_FLANDERS', 'TXT_KEY_IMPROVEMENT_MARSH_FLANDERS_HELP', 'ART_DEF_IMPROVEMENT_POLDER', 0, 'EXPANSION_TERRAIN_ATLAS';

UPDATE Improvements
SET Coastal = 1
WHERE Type = 'IMPROVEMENT_MARSH_FLANDERS';

INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType)
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TERRAIN_GRASS' UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TERRAIN_PLAINS' UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TERRAIN_DESERT' UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TERRAIN_TUNDRA' UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'TERRAIN_SNOW';

INSERT INTO Improvement_Flavors (ImprovementType, FlavorType, Flavor)
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'FLAVOR_GROWTH', 10 UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'FLAVOR_CULTURE', 5;
	
INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield)
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'YIELD_FOOD', 3 UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'YIELD_PRODUCTION', 2 UNION ALL
SELECT 'IMPROVEMENT_MARSH_FLANDERS', 'YIELD_GOLD', 1;				